/*
 * This source file was generated by the Gradle 'init' task
 */
package tucil3_13524018_13524084;

import tucil3_13524018_13524084.Core.*;
import tucil3_13524018_13524084.FileReader.*;
import tucil3_13524018_13524084.GameEventException.GameOverException;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.IOException;
import java.util.List;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App{
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String filePath = "../app/data/1-map.txt";
        try {
            String content = Files.readString(Paths.get(filePath));
            Board g = FileIO.readInput(content);
            g.movePlayer(Direction.UP);
            g.movePlayer(Direction.RIGHT);
            g.movePlayer(Direction.DOWN);
            g.printBoard();
            System.out.println("Berhasil memuat map dari: " + filePath);
            System.out.println("Total tiles: " + g.getTiles().size());
        } catch (IOException e) {
            System.err.println("Gagal membaca file! Pastikan path benar: " + e.getMessage());
        } catch (GameOverException e){
            System.err.println(e.getMessage());
        }
        catch (IllegalArgumentException | IllegalStateException e) {
            System.err.println("Format map salah: " + e.getMessage());
        } 
    }
}
