/*
 * This source file was generated by the Gradle 'init' task
 */
package tucil3_13524018_13524084;

import tucil3_13524018_13524084.Core.*;
import tucil3_13524018_13524084.FileReader.*;
import tucil3_13524018_13524084.GameEventException.GameOverException;
import tucil3_13524018_13524084.Solver.AStarSolver;
import tucil3_13524018_13524084.Solver.GBFSSolver;
import tucil3_13524018_13524084.Solver.UCSSolver;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.IOException;
import java.util.List;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String filePath = "../app/data/1-map.txt";
        try {
            String content = Files.readString(Paths.get(filePath));
            Board board = FileIO.readInput(content);

            AStarSolver solverAStar = new AStarSolver(board);
            List<Direction> directions = solverAStar.solve();
            for (Direction direction : directions) {

                board.movePlayer(direction);
                board.printBoard();
                System.out.println(board.getPlayer().getTotalCost());
            }
        } catch (IOException e) {
            System.err.println("Gagal membaca file! Pastikan path benar: " + e.getMessage());
        } catch (IllegalArgumentException | IllegalStateException e) {
            System.err.println("Format map salah: " + e.getMessage());
        }catch(GameOverException e){
            System.err.println(e.getMessage());
        }
    }
}
