/*
 * This source file was generated by the Gradle 'init' task
 */
package tucil3_13524018_13524084;

import tucil3_13524018_13524084.Core.*;
import tucil3_13524018_13524084.FileReader.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.IOException;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        String filePath = "../app/data/1-map.txt";
        try {
            String content = Files.readString(Paths.get(filePath));
            Grid g = FileIO.readInput(content);
            g.printGrid();
            System.out.println("Berhasil memuat map dari: " + filePath);
            System.out.println("Total tiles: " + g.getTiles().size());
        } catch (IOException e) {
            System.err.println("Gagal membaca file! Pastikan path benar: " + e.getMessage());
        } catch (IllegalArgumentException | IllegalStateException e){
            System.err.println("Format map salah: " + e.getMessage());
        }
    }
}
